import "server-only";

import path from "node:path";

import type { Database } from "./client";

export const MIGRATIONS_FOLDER = path.join(process.cwd(), "src", "admin", "server", "db", "migrations");

/**
 * Applies pending SQL migrations (generated by `npm run db:generate`). Runs on the first database
 * access of every server instance, so deploys need no manual step. Two instances racing on a fresh
 * database: the loser fails inside its transaction, retries, and finds everything applied.
 */
export async function runMigrations(db: Database, driver: "postgres" | "pglite") {
  const migrate =
    driver === "pglite"
      ? (await import("drizzle-orm/pglite/migrator")).migrate
      : (await import("drizzle-orm/postgres-js/migrator")).migrate;

  for (let attempt = 1; ; attempt++) {
    try {
      // The two migrators share an API; the database object is driver-specific at runtime.
      await migrate(db as never, { migrationsFolder: MIGRATIONS_FOLDER });
      return;
    } catch (error) {
      if (attempt >= 3) throw error;
      await new Promise((resolve) => setTimeout(resolve, 400 * attempt));
    }
  }
}
